# Generated by Django 2.2.3 on 2019-07-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190715_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='introduction',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='place',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
