# Generated by Django 2.2.3 on 2019-07-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190715_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meetingtime',
        ),
    ]
