# Generated by Django 2.2.3 on 2019-07-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190716_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='introduction',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='place',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
