# Generated by Django 2.2.3 on 2019-07-17 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_auto_20190716_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='user_invitation',
            field=models.ManyToManyField(blank=True, related_name='meeting_invitation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='user_participation',
            field=models.ManyToManyField(blank=True, related_name='meeting_participation', to=settings.AUTH_USER_MODEL),
        ),
    ]
