# Generated by Django 2.2.3 on 2019-07-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190717_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
