# Generated by Django 2.2.3 on 2019-07-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='endtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meetingdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='starttime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
