# Generated by Django 2.2.3 on 2019-07-16 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_meeting_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_column', to=settings.AUTH_USER_MODEL),
        ),
    ]
